# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20171230_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
