# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 08:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20180102_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Item10Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item10Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item2Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item2Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item3Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item3Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item4Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item4Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item5Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item5Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item6Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item6Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item7Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item7Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item8Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item8Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item9Bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Item9Value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='MainSwitch',
            field=models.BooleanField(default=0),
        ),
    ]
