# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_usermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
