# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_usermodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(default='helloworld', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
