# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 07:28
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20180103_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='label',
            field=django_extensions.db.fields.RandomCharField(blank=True, db_index=True, editable=False, length=16, unique=True),
        ),
    ]
